# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-12 09:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('areaOfInterest', models.CharField(max_length=20)),
                ('expertise', models.IntegerField()),
                ('urls', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
    ]
