# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-15 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collobSearch', '0002_auto_20160312_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(db_index=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='UrlMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areaOfInterest', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='searcher',
            name='urls',
        ),
        migrations.AlterField(
            model_name='searcher',
            name='areaOfInterest',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='urlmap',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collobSearch.Searcher'),
        ),
        migrations.AddField(
            model_name='keyval',
            name='aoi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collobSearch.UrlMap'),
        ),
    ]
