# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collobSearch', '0003_auto_20160315_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyval',
            old_name='aoi',
            new_name='urlmap',
        ),
        migrations.RenameField(
            model_name='urlmap',
            old_name='username',
            new_name='searcher',
        ),
    ]
