# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collobSearch', '0004_auto_20160316_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyval',
            name='id',
        ),
        migrations.RemoveField(
            model_name='searcher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='urlmap',
            name='id',
        ),
        migrations.AlterField(
            model_name='keyval',
            name='url',
            field=models.CharField(max_length=240, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='keyval',
            name='urlmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='collobSearch.UrlMap'),
        ),
        migrations.AlterField(
            model_name='searcher',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='areaOfInterest',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='collobSearch.Searcher'),
        ),
    ]
