# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collobSearch', '0005_auto_20160316_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyval',
            name='urlmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, to='collobSearch.UrlMap'),
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='areaOfInterest',
            field=models.CharField(max_length=50, primary_key=True),
        ),
    ]
