# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collobSearch', '0007_auto_20160316_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyval',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='urlmap',
            name='id',
            field=models.AutoField(default='1', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keyval',
            name='urlmap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collobSearch.UrlMap'),
        ),
        migrations.AlterField(
            model_name='urlmap',
            name='searcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collobSearch.Searcher'),
        ),
    ]
